In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!pip install --upgrade "dask[dataframe]"

Requirement already satisfied: dask[dataframe] in /usr/local/lib/python3.12/dist-packages (2025.5.0)
Collecting dask[dataframe]
  Downloading dask-2025.9.0-py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: click>=8.1 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]) (8.2.1)
Requirement already satisfied: cloudpickle>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]) (3.1.1)
Requirement already satisfied: fsspec>=2021.09.0 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]) (2025.3.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]) (25.0)
Requirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]) (6.0.2)
Requirement already satisfied: toolz>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]) (0.12.1)
Requirement already satisfied: pandas>=2.0 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]) (2.2.2)
Requirement already satisfied: pyarrow>=14.0.1 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]) (18.1.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->dask[dataframe]) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->dask[dataframe]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->dask[dataframe]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->dask[dataframe]) (2025.2)
Requirement already satisfied: locket in /usr/local/lib/python3.12/dist-packages (from partd>=1.4.0->dask[dataframe]) (1.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.0->dask[dataframe]) (1.17.0)
Downloading dask-2025.9.0-py3-none-any.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 14.9 MB/s eta 0:00:00
Installing collected packages: dask
  Attempting uninstall: dask
    Found existing installation: dask 2025.5.0
    Uninstalling dask-2025.5.0:
      Successfully uninstalled dask-2025.5.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
distributed 2025.5.0 requires dask==2025.5.0, but you have dask 2025.9.0 which is incompatible.
rapids-dask-dependency 25.6.0 requires dask==2025.5.0, but you have dask 2025.9.0 which is incompatible.
Successfully installed dask-2025.9.0

In [ ]:
!pip install --upgrade "dask[distributed]"

Requirement already satisfied: dask[distributed] in /usr/local/lib/python3.12/dist-packages (2025.9.0)
Requirement already satisfied: click>=8.1 in /usr/local/lib/python3.12/dist-packages (from dask[distributed]) (8.2.1)
Requirement already satisfied: cloudpickle>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from dask[distributed]) (3.1.1)
Requirement already satisfied: fsspec>=2021.09.0 in /usr/local/lib/python3.12/dist-packages (from dask[distributed]) (2025.3.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from dask[distributed]) (25.0)
Requirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from dask[distributed]) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from dask[distributed]) (6.0.2)
Requirement already satisfied: toolz>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from dask[distributed]) (0.12.1)
Collecting distributed==2025.9.0 (from dask[distributed])
  Downloading distributed-2025.9.0-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: jinja2>=2.10.3 in /usr/local/lib/python3.12/dist-packages (from distributed==2025.9.0->dask[distributed]) (3.1.6)
Requirement already satisfied: locket>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from distributed==2025.9.0->dask[distributed]) (1.0.0)
Requirement already satisfied: msgpack>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from distributed==2025.9.0->dask[distributed]) (1.1.1)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from distributed==2025.9.0->dask[distributed]) (5.9.5)
Requirement already satisfied: sortedcontainers>=2.0.5 in /usr/local/lib/python3.12/dist-packages (from distributed==2025.9.0->dask[distributed]) (2.4.0)
Requirement already satisfied: tblib>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from distributed==2025.9.0->dask[distributed]) (3.1.0)
Requirement already satisfied: tornado>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from distributed==2025.9.0->dask[distributed]) (6.4.2)
Requirement already satisfied: urllib3>=1.26.5 in /usr/local/lib/python3.12/dist-packages (from distributed==2025.9.0->dask[distributed]) (2.5.0)
Requirement already satisfied: zict>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from distributed==2025.9.0->dask[distributed]) (3.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.10.3->distributed==2025.9.0->dask[distributed]) (3.0.2)
Downloading distributed-2025.9.0-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 9.7 MB/s eta 0:00:00
Installing collected packages: distributed
  Attempting uninstall: distributed
    Found existing installation: distributed 2025.5.0
    Uninstalling distributed-2025.5.0:
      Successfully uninstalled distributed-2025.5.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
rapids-dask-dependency 25.6.0 requires dask==2025.5.0, but you have dask 2025.9.0 which is incompatible.
rapids-dask-dependency 25.6.0 requires distributed==2025.5.0, but you have distributed 2025.9.0 which is incompatible.
Successfully installed distributed-2025.9.0

In [ ]:
!pip install --upgrade pyarrow

Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (18.1.0)
Collecting pyarrow
  Downloading pyarrow-21.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.3 kB)
Downloading pyarrow-21.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (42.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.8/42.8 MB 22.4 MB/s eta 0:00:00
Installing collected packages: pyarrow
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 18.1.0
    Uninstalling pyarrow-18.1.0:
      Successfully uninstalled pyarrow-18.1.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cudf-cu12 25.6.0 requires pyarrow<20.0.0a0,>=14.0.0; platform_machine == "x86_64", but you have pyarrow 21.0.0 which is incompatible.
pylibcudf-cu12 25.6.0 requires pyarrow<20.0.0a0,>=14.0.0; platform_machine == "x86_64", but you have pyarrow 21.0.0 which is incompatible.
Successfully installed pyarrow-21.0.0

## Dados

**Descrição das colunas:**  
timestamp,user_id,action,adId,campaignId

**Amostra:**  
2016-09-21 22:11:00,7c74953c-66cc-48bd-9d02-a02bf039cf3f,click,adId_09,campaignId_01  
2016-06-25 18:29:00,676a083e-2f8e-4ff2-9ec2-270f7f9d6033,view,adId_09,campaignId_02  
2016-02-14 19:03:00,77158997-0dfa-48b7-9149-973dc151ef8d,click,adId_02,campaignId_02  
2016-03-26 06:27:00,78aa2467-b502-413b-94e9-04ec8210bd13,click,adId_07,campaignId_03

**Path:**  
data/ad_action.csv

## Atividade 1

Qual é o anúncio mais popular, ou seja, com mais eventos independente do action?

**Resposta:**  
adId_06

## Atividade 2

Quantos clicks gerou a campanha mais popular?

**Resposta:**  
63983 clicks

## Atividade 3

Algum usuário só visualizou? Quantas actions foram enviadas por usuário que só visualizou?

**Resposta:**  
Sim, o usuário d99871cb-98b7-4ac5-97a5-b9a26c0f897b enviou apenas 1 action

## Atividade 4

Dos 10411 usuários, quantos usuários clicam mais que visualizam?

**Resposta:**  
10078

## Atividade 5

Calcule a quantidade de clicks por dia da semana e apresente o resultado em ordem decrescente de quantidade de clicks.

PS: Nesse exemplo, 0 é segunda-feira e 6 é domingo. Você pode usar outro padrão, contanto que os dias da semana estejam correspondentes a resposta abaixo

**Resposta**  
27918, 4  
25424, 5  
25028, 0  
25027, 3  
25020, 6  
24973, 1  
24915, 2

## Atividade 6

Algum anúncio teve um crescimento de clicks ao longo das 3 campanhas?

**Resposta:**  
Sim, o anúncio adId_07

In [ ]:
# IMPORTS, CRIAÇÃO DO CLUSTER E CARREGAMENTO DOS DADOS AQUI
import dask.dataframe as dd

from dask.distributed import Client, LocalCluster

In [ ]:
cluster = LocalCluster()
client = Client(cluster)
client

INFO:distributed.http.proxy:To route to workers diagnostics web server please install jupyter-server-proxy: python -m pip install jupyter-server-proxy
INFO:distributed.scheduler:State start
INFO:distributed.scheduler:  Scheduler at:     tcp://127.0.0.1:44193
INFO:distributed.scheduler:  dashboard at:  http://127.0.0.1:8787/status
INFO:distributed.scheduler:Registering Worker plugin shuffle
INFO:distributed.nanny:        Start Nanny at: 'tcp://127.0.0.1:32853'
INFO:distributed.nanny:        Start Nanny at: 'tcp://127.0.0.1:42145'
INFO:distributed.scheduler:Register worker addr: tcp://127.0.0.1:45797 name: 0
INFO:distributed.scheduler:Starting worker compute stream, tcp://127.0.0.1:45797
INFO:distributed.core:Starting established connection to tcp://127.0.0.1:50550
INFO:distributed.scheduler:Register worker addr: tcp://127.0.0.1:39133 name: 1
INFO:distributed.scheduler:Starting worker compute stream, tcp://127.0.0.1:39133
INFO:distributed.core:Starting established connection to tcp://127.0.0.1:50556
INFO:distributed.scheduler:Receive client connection: Client-305bd674-9102-11f0-80b1-0242ac1c000c
INFO:distributed.core:Starting established connection to tcp://127.0.0.1:50558

In [ ]:
df = dd.read_csv(
    'drive/MyDrive/data/ad_action.csv',
    header=None,
    parse_dates=[0])
df.columns = ['timestamp', 'user_id', 'action', 'adId', 'campaignId']
df

Dask DataFrame Structure:
                    timestamp user_id  action    adId campaignId
npartitions=1
               datetime64[ns]  string  string  string     string
                          ...     ...     ...     ...        ...
Dask Name: operation, 3 expressions
Expr=ColumnsSetter(frame=ArrowStringConversion(frame=FromMapProjectable(df633d0)), columns=['timestamp', 'user_id', 'action', 'adId', 'campaignId'])

In [ ]:
df.head()

,timestamp,user_id,action,adId,campaignId
0,2016-09-21 22:11:00,7c74953c-66cc-48bd-9d02-a02bf039cf3f,click,adId_09,campaignId_01
1,2016-06-25 18:29:00,676a083e-2f8e-4ff2-9ec2-270f7f9d6033,view,adId_09,campaignId_02
2,2016-02-14 19:03:00,77158997-0dfa-48b7-9149-973dc151ef8d,click,adId_02,campaignId_02
3,2016-03-26 06:27:00,78aa2467-b502-413b-94e9-04ec8210bd13,click,adId_07,campaignId_03
4,2016-01-02 04:57:00,fef9a98c-d73e-48ef-b2cb-766ba85dc3e3,view,adId_02,campaignId_02

## Resposta Atividade 1

Qual é o anúncio mais popular, ou seja, com mais eventos independente do action?

**Resposta:**  
adId_06

In [ ]:
# ESCREVA SEU CÓDIGO AQUI

In [ ]:
df_aid = df.groupby("adId")\
 ["action"]\
 .count()\
 .nlargest(1)\
 .rename("count")\
 .reset_index()

df_aid.compute()

      adId  count
0  adId_06  29188

## Resposta Atividade 2

Quantos clicks gerou a campanha mais popular?

**Resposta:**  
63983 clicks

In [ ]:
# ESCREVA SEU CÓDIGO AQUI

In [ ]:
df_campaign = df[df["action"] == "click"]\
 .groupby("campaignId")\
 ["action"]\
 .count()\
 .nlargest(1)\
 .rename("count")\
 .reset_index()

df_campaign.compute()

      campaignId  count
0  campaignId_02  63983

## Resposta Atividade 3

Algum usuário só visualizou? Quantas actions foram enviadas por usuário que só visualizou?

**Resposta:**  
Sim, o usuário d99871cb-98b7-4ac5-97a5-b9a26c0f897b enviou apenas 1 action

In [ ]:
# ESCREVA SEU CÓDIGO AQUI

In [ ]:
result_df = df.groupby('user_id')\
  ['action']\
  .value_counts()\
  .rename('events_count')\
  .reset_index()\
  .categorize(columns=['action'])\
  .pivot_table(index='user_id', columns='action', values='events_count', aggfunc='sum')\
  .persist()
result_df.compute()

action                                click  view
user_id
00023420-6ead-4633-ba35-b1e0c5abe269     14     6
000f0200-0918-4148-866c-341bd6eec354      8     2
00130041-b283-4154-8406-b4079dfe7c88     25     9
00317295-4aa4-46ef-a849-26ade50bf3e7     26     7
0031aa2d-5988-4024-95d4-42ae50c09955     21     9
...                                     ...   ...
ffe0582f-44ef-451d-81a6-b9ac3d3d4fa5     16    10
ffe4204d-72b7-400a-b66e-c6171e00062e     13    13
fff18213-eeaf-41de-91ff-79e04577df67     17     6
fff3e8a9-b2d0-4b3c-892e-4bb224feb970     13     8
fff3f92a-9605-4db3-b485-640f74bf2ac3     30    12

[10411 rows x 2 columns]

In [ ]:
result_df[result_df['click']==0].compute()

action                                click  view
user_id
d99871cb-98b7-4ac5-97a5-b9a26c0f897b      0     1

## Resposta Atividade 4

Dos 10411 usuários, quantos usuários clicam mais que visualizam?

**Resposta:**  
10078

In [ ]:
# ESCREVA SEU CÓDIGO AQUI

In [ ]:
result_df[result_df['click']>result_df['view']].head()

action                                click  view
user_id
00023420-6ead-4633-ba35-b1e0c5abe269     14     6
000f0200-0918-4148-866c-341bd6eec354      8     2
00130041-b283-4154-8406-b4079dfe7c88     25     9
00317295-4aa4-46ef-a849-26ade50bf3e7     26     7
0031aa2d-5988-4024-95d4-42ae50c09955     21     9

In [ ]:
len(result_df[result_df['click']>result_df['view']])

10078

## Resposta Atividade 5

Calcule a quantidade de clicks por dia da semana e apresente o resultado em ordem decrescente de quantidade de clicks.

PS: Nesse exemplo, 0 é segunda-feira e 6 é domingo. Você pode usar outro padrão, contanto que os dias da semana estejam correspondentes a resposta abaixo

**Resposta**  
27918, 4  
25424, 5  
25028, 0  
25027, 3  
25020, 6  
24973, 1  
24915, 2

In [ ]:
# ESCREVA SEU CÓDIGO AQUI

In [ ]:
df['week_day'] = df['timestamp'].dt.weekday
df.head()

,timestamp,user_id,action,adId,campaignId,week_day
0,2016-09-21 22:11:00,7c74953c-66cc-48bd-9d02-a02bf039cf3f,click,adId_09,campaignId_01,2
1,2016-06-25 18:29:00,676a083e-2f8e-4ff2-9ec2-270f7f9d6033,view,adId_09,campaignId_02,5
2,2016-02-14 19:03:00,77158997-0dfa-48b7-9149-973dc151ef8d,click,adId_02,campaignId_02,6
3,2016-03-26 06:27:00,78aa2467-b502-413b-94e9-04ec8210bd13,click,adId_07,campaignId_03,5
4,2016-01-02 04:57:00,fef9a98c-d73e-48ef-b2cb-766ba85dc3e3,view,adId_02,campaignId_02,5

In [1]:
df[df['action']=='click']\
  .groupby('week_day')\
  ['timestamp']\
  .count()\
  .nlargest(7)\
  .compute()

NameError: name 'df' is not defined

## Resposta Atividade 6

Algum anúncio teve um crescimento de clicks ao longo das 3 campanhas?

**Resposta:**  
Sim, o anúncio adId_07

In [ ]:
# ESCREVA SEU CÓDIGO AQUI